# Generated by Django 3.0 on 2022-05-22 11:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('centro', models.CharField(default=None, max_length=150)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(default=None, max_length=1)),
            ],
            options={
                'ordering': ('curso',),
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=50)),
                ('tipo', models.IntegerField(default=None, null=True)),
                ('enunciado', models.CharField(default=None, max_length=1000)),
                ('nsoluciones', models.IntegerField(default=None, null=True)),
                ('soluciones', models.CharField(default=None, max_length=1000)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
            ],
            options={
                'ordering': ('curso', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('centro', models.CharField(default=None, max_length=150)),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.IntegerField(default=None, null=True)),
                ('titulo', models.CharField(default=None, max_length=150)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
            ],
            options={
                'ordering': ('tema', 'curso'),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=50)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
                ('tema', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Tema')),
            ],
            options={
                'ordering': ('curso', 'tema', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=50)),
                ('texto', models.CharField(default=None, max_length=10000)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
                ('tema', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Tema')),
            ],
            options={
                'ordering': ('curso', 'tema', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default=None, max_length=200)),
                ('tiempo', models.FloatField(default=None, null=True)),
                ('alumno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Alumno')),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
                ('ejercicios', models.ManyToManyField(default=None, to='divermat.Ejercicio')),
                ('temas', models.ManyToManyField(default=None, to='divermat.Tema')),
            ],
            options={
                'ordering': ('curso', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=15)),
                ('centro', models.CharField(default=None, max_length=150)),
                ('ano_academico', models.DateField()),
                ('n_alumnos', models.IntegerField(default=None, null=True)),
                ('curso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso')),
                ('profesor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Profesor')),
            ],
            options={
                'ordering': ('ano_academico', 'curso', 'nombre', 'centro'),
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='clase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Clase'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso'),
        ),
    ]
