# Generated by Django 3.0 on 2022-05-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0002_ejercicio_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='numexamen',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
