# Generated by Django 3.0 on 2022-06-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0003_alumno_numexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='tipo',
            field=models.BooleanField(choices=[(1, 'Profesor'), (2, 'Alumno')], default=1, null=True),
        ),
        migrations.AddField(
            model_name='profesor',
            name='tipo',
            field=models.BooleanField(choices=[(1, 'Profesor'), (2, 'Alumno')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='centro',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='curso',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Curso'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='centro',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
