# Generated by Django 3.0 on 2022-12-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0004_auto_20220628_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='password_temporal',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='tipo',
            field=models.BooleanField(choices=[(0, 'Profesor'), (1, 'Alumno')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='tipo',
            field=models.BooleanField(choices=[(0, 'Profesor'), (1, 'Alumno')], default=1, null=True),
        ),
    ]
