# Generated by Django 3.0 on 2023-01-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0005_auto_20221230_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_ejercicios', models.IntegerField(default=0, null=True)),
                ('acierto', models.FloatField(default=0.0, null=True)),
                ('alumno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Alumno')),
                ('ejercicios', models.ManyToManyField(default=None, to='divermat.Ejercicio')),
                ('tema', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Tema')),
            ],
            options={
                'ordering': ('tema',),
            },
        ),
    ]
