# Generated by Django 3.0 on 2023-01-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0007_clase_ejercicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='solucion_correcta',
            field=models.CharField(default=None, max_length=1024),
        ),
    ]
