# Generated by Django 3.0 on 2023-01-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0010_auto_20230128_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='ejercicios',
        ),
        migrations.CreateModel(
            name='SeguimientoEjercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divermat.Ejercicio')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divermat.Examen')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenTema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divermat.Ejercicio')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divermat.Examen')),
            ],
        ),
    ]
