# Generated by Django 3.0 on 2023-01-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0011_auto_20230128_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='ejercicios',
            field=models.ManyToManyField(to='divermat.Ejercicio'),
        ),
        migrations.DeleteModel(
            name='ExamenEjercicio',
        ),
    ]
