# Generated by Django 3.0 on 2023-01-28 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0012_auto_20230128_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='ejercicios',
            field=models.ManyToManyField(default=None, to='divermat.Ejercicio'),
        ),
    ]
