# Generated by Django 3.0 on 2023-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0013_auto_20230128_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimientoejercicio',
            name='ejercicio',
        ),
        migrations.RemoveField(
            model_name='seguimientoejercicio',
            name='examen',
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='ejercicios',
            field=models.ManyToManyField(default=None, to='divermat.Ejercicio'),
        ),
        migrations.DeleteModel(
            name='ExamenTema',
        ),
        migrations.DeleteModel(
            name='SeguimientoEjercicio',
        ),
    ]
