# Generated by Django 3.0 on 2023-02-02 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0014_auto_20230128_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjercicioUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluciones_seleccionadas', models.CharField(default=None, max_length=1000)),
                ('alumno', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Alumno')),
                ('ejercicio', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.Ejercicio')),
            ],
        ),
        migrations.AlterField(
            model_name='examen',
            name='ejercicios',
            field=models.ManyToManyField(default=None, to='divermat.EjercicioUsuario'),
        ),
    ]
