# Generated by Django 3.0 on 2023-02-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0015_auto_20230202_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='nota',
            field=models.FloatField(default=None, null=True),
        ),
    ]
