# Generated by Django 3.0 on 2023-02-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0016_examen_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='media/videos'),
        ),
    ]
