# Generated by Django 3.0 on 2023-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0017_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='resumen',
            field=models.FileField(blank=True, null=True, upload_to='media/resumenes'),
        ),
    ]
