# Generated by Django 3.0 on 2023-02-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0021_auto_20230204_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='nota',
            field=models.FloatField(default=0, null=True),
        ),
    ]
