# Generated by Django 3.0 on 2023-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0022_auto_20230212_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='fin',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='inicio',
            field=models.TimeField(default=None),
        ),
    ]
