# Generated by Django 3.0 on 2023-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0024_auto_20230212_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='inicio',
            field=models.TimeField(default=None),
        ),
    ]
