# Generated by Django 3.0 on 2023-02-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0025_auto_20230212_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fin',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='inicio',
            field=models.DateTimeField(default=None),
        ),
    ]
