# Generated by Django 3.0 on 2023-02-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0026_auto_20230212_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='cronometrado',
            field=models.BooleanField(choices=[(0, 'Si'), (1, 'No')], default=1, null=True),
        ),
    ]
