# Generated by Django 3.0 on 2023-02-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0028_auto_20230217_1950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
