# Generated by Django 3.0 on 2023-02-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0030_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foto',
            options={},
        ),
        migrations.RemoveField(
            model_name='foto',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='tema',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='foto',
            field=models.FileField(blank=True, upload_to='media/fotos/%y'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='perfil',
            field=models.BooleanField(default=True, max_length=50),
        ),
    ]
