# Generated by Django 3.0 on 2023-02-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0034_remove_ejerciciousuario_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejerciciousuario',
            name='resultado',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
