# Generated by Django 3.0 on 2023-04-05 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0035_ejerciciousuario_resultado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
