# Generated by Django 3.0 on 2023-05-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0036_delete_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ('curso', 'tema')},
        ),
    ]
