# Generated by Django 3.0 on 2023-05-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0038_auto_20230511_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, upload_to='media/videos/%y'),
        ),
        migrations.DeleteModel(
            name='VideoFile',
        ),
    ]
