# Generated by Django 3.0 on 2023-05-11 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0039_auto_20230511_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoFile', models.FileField(blank=True, upload_to='media/videos/%y')),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='divermat.VideoFile'),
        ),
    ]
