# Generated by Django 3.0 on 2023-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divermat', '0040_auto_20230511_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='tituloFile',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
